version: '3.8'

services:
  web:
    build: multi-stage-build
    ports:
      - "5002:5002"
    depends_on:
      - mydb

  mydb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw