name: Doker hub 

on: 
  release: 
    types: [published]  


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
    - name: checkcode 
      uses: actions/checkout@v2
    - name: login to docker hub 
      uses: docker/login-action@v3
      with: 
         username: ${{vars.USERNAME}}
         password: ${{vars.TOKEN}}
    
    - name: metadata for docker 
      id: meta
      uses: docker/metadata-action@v5
      with: 
        images: omar252/continious
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          repository:
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
 